version: '3'

services:
  backend:
    env_file: ".env"
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "rafart-app-backend"
    ports: 
      - "8000:8000"
    volumes:
      - './:/app'
      - '/app/node_modules'


  

