version: '3'

services:
  backend:
    env_file: ".env"
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    image: "rafart-app-backend"
    environment:
     - PORT
     - production: true
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - './:/app'
      - '/app/node_modules'

