version: "3.1"

services:
  db-rafart:
    image: postgres:11.3
    restart: always
    volumes:
      - "pg-db-rafart:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "pg-db-rafart"
    ports:
      - "5432:5432"
    networks:
      - backend

  redis-rafart:
    image: "redis:latest"
    restart: always
    ports:
      - "6380:6379" # Make host port 6380 to avoid conflict with local redis service. Mapped to 6379 on the container.
    networks:
      - backend
    volumes:
      - "redis-data-rafart:/data" # Mount a volume to persist data
    command: redis-server --appendonly yes # Enable append-only file for persistence

  nodeapp-rafart:
    image: "node:16"
    build: ./server
    working_dir: "/app"
    volumes:
      - "./server:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db-rafart
      - redis-rafart
    environment:
      NODE_ENV: "development"
      SECRET: ${SECRET}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER_NAME: ${PG_USER_NAME}
      PG_DATABASE: ${PG_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TEST_STRIPE_SECRET_KEY: ${TEST_STRIPE_SECRET_KEY}
      IAM_ACCESS_ID: ${IAM_ACCESS_ID}
      IAM_SECRET: ${IAM_SECRET}
      AWS_REGION: ${AWS_REGION}
      BUCKET: ${BUCKET}
    command: "yarn dev"
    networks:
      - backend

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nodeapp-rafart
    networks:
      - backend

volumes:
  pg-db-rafart:
  redis-data-rafart: # Declare the volume for Redis data persistence

networks:
  backend:
    driver: bridge
